using System.ComponentModel.DataAnnotations;

namespace OpenAiChat.Api.Models;

/// <summary>Payload sent by the client to POST /api/chat.</summary>
public sealed class ChatRequest
{
    /// <summary>The user's message to forward to OpenAI.</summary>
    [Required(AllowEmptyStrings = false, ErrorMessage = "message is required and cannot be empty.")]
    [MaxLength(4000, ErrorMessage = "message must not exceed 4 000 characters.")]
    public string Message { get; set; } = string.Empty;
}

/// <summary>Payload returned to the client after a successful OpenAI call.</summary>
public sealed class ChatResponse
{
    /// <summary>The text generated by OpenAI.</summary>
    public string Response { get; set; } = string.Empty;
}

/// <summary>
/// Standardised error payload (RFC 7807 style) returned on failures.
/// </summary>
public sealed class ErrorResponse
{
    public string Error { get; set; } = string.Empty;
    public string? Detail { get; set; }
}
